on: push
name: Publish Website
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.cluster014.hosting.ovh.net
        username: mortemou
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /www/
